### ISSUE TITLE
Attempt to bump transformers to latest in LTS-11 or make an issue on why it cannot be bumped

### ISSUE THREAD

**Issue by mihaimaruseac** [commercialhaskell/lts-haskell#138]
https://twitter.com/mxavier/status/1009474496510562305

Seems `transformers-0.5.2.0` has a space leak which is fixed by the time of latest transformers. We should attempt to bump the package to a version which doesn't.

**Comment by DanBurton** [comment]
The reason we don't update `transformers` is because the `ghc` package depends on `transformers`. We cannot rebuild the `ghc` package, so it and its dependencies (including `transformers`) are stuck to the versions shipped with ghc.

I believe there's an ongoing issue to address this issue with the `ghc` package.

**Comment by snoyberg** [comment]
This can't be done without breaking lots of things, closing.
