### ISSUE TITLE
Adding ghc-parser and ihaskell to lts-14

### ISSUE THREAD

**Issue by vaibhavsagar** [commercialhaskell/lts-haskell#249]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

~Unfortunately the test suite doesn't pass on the latest Stack due to https://github.com/commercialhaskell/stack/issues/4896, but you can see it working on an older version of Stack at e.g. https://travis-ci.org/gibiansky/IHaskell/jobs/589730604~ This has been fixed now!

**Comment by qrilka** [comment]
@vaibhavsagar did you test the code using Stack-2.1.3? It includes #4921 which is supposed to fix #4896

**Comment by vaibhavsagar** [comment]
Yes, we did: https://github.com/gibiansky/IHaskell/pull/1093.

**Comment by vaibhavsagar** [comment]
Now that we've resolved this, is there anything further you need from me to get IHaskell in `lts-14`?

**Comment by qrilka** [comment]
@vaibhavsagar I just checked and I see both `IHaskell` and `ghc-parser` in lts-14.7 - https://www.stackage.org/lts-14.7/package/ihaskell-0.10.0.0
I see it was disabled in nightlies because of incompatibility with GHC-8.8.1. I guess your latest released fixed that so you could add a PR removing `ihaskell < 0` from https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml but that's for nightly and I for LTS-15. As for LTS-14 I don't see any problems.

**Comment by vaibhavsagar** [comment]
Thank you!

**Comment by qrilka** [comment]
Do we have anything to do in this ticket or we could just close it @vaibhavsagar ?

**Comment by vaibhavsagar** [comment]
Closing it sounds good to me!
