### ISSUE TITLE
prepare for lts-23 with ghc-9.8

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/lts-haskell#382]
Current LTS 22 has reached 22.28, so it time to think about and plan for the release LTS 23.

We are not sure yet when GHC 9.8.3 will be released: personally I am tempted to wait for it
(this would include avoiding downgrading Cabal for example), but it might take too long?

Current ghc-9.6 and lts-22 seems pretty stable and generally working well,
but of course there are many updates in Nightly:
https://www.stackage.org/diff/lts-22.28/nightly-2024-07-08

Let's discuss more here...

See also related: commercialhaskell/stackage#7462

**Comment by juhp** [comment]
@bergmark, how was [lts-22-build-constraints.yaml](https://github.com/commercialhaskell/lts-haskell/blob/master/build-constraints/lts-22-build-constraints.yaml) bootstrapped or created?

**Comment by ysangkok** [comment]
I don't think 9.8.3 is likely to be released any time soon, since there [has been no commits to the 9.8 branch since May](https://gitlab.haskell.org/ghc/ghc/-/tree/ghc-9.8?ref_type=heads). And [9.8.3 is scheduled to get released after 9.10.2](https://www.haskell.org/ghc/blog/20240521-ghc-release-priorities.html). But 9.10 is scheduled for a release before 9.8. But [9.10 also hasn't seen commits since May](https://gitlab.haskell.org/ghc/ghc/-/tree/ghc-9.10?ref_type=heads).

Looking at the commits in the 9.8 branch, you can see that 9.8.2 is in there. So it should be the right branch (and not just the branches for the .1 releases)

**Comment by juhp** [comment]
I think we could release lts-23 before long, but we need to commit @bergmark 's lts-build-constraints tool first - the rest should be relatively straightforward.

**Comment by juhp** [comment]
https://www.stackage.org/lts-23.0 released a week ago
