### ISSUE TITLE
Why is there an upper bound on Opaleye

### ISSUE THREAD

**Issue by tomjaguarpaw** [commercialhaskell/lts-haskell#388]
I'm the Opaelye maintainer. I see there's an upper bound on Opaleye

https://github.com/commercialhaskell/lts-haskell/blob/b6387283036c5a94b5547eb909d1a233d240a13c/build-constraints/lts-22-build-constraints.yaml#L1761

as imposed in this commit: https://github.com/commercialhaskell/lts-haskell/commit/1cfddfabcbb54c2e4518d88e2423ae0fa402dcc2#diff-58e26863dfb39461dede8943ad0bd4648278048ebe574a061d83701e49abb2a2

Why? Is there something I should be doing to make `opaleye-0.10.4.0` suitable for LTS Haskell?

**Comment by mihaimaruseac** [comment]
This is because

uuid-types-1.0.5.1 ([changelog](http://hackage.haskell.org/package/uuid-types-1.0.5.1/changelog)) (Grandfathered dependencies) is out of bounds for:
- [ ] opaleye-0.10.4.0 (>=1.0.6 && < 1.1). Tom Ellis <tom-stackage@jaguarpaw.co.uk> @tomjaguarpaw. Used by: library

On LTS we don't notify owners again (maybe we should?), we just try to make the snapshot consistent. LTS starts with the state of the nightly when the first LTS in the series starts and after that we only add bounds to do minimal changes to the snapshot.

**Comment by mihaimaruseac** [comment]
uuid-types got an upper bound in cf462100175b593bc1ed2eaee9cc66f052782d4b for similar reasons.

**Comment by tomjaguarpaw** [comment]
Thanks, I revised `opaleye-0.10.4.0` to allow `uuid-types >= 1.0.5`: https://hackage.haskell.org/package/opaleye-0.10.4.0

Is there anything I need to do to get the upper bound on Opaleye removed in the LTS?

**Comment by tomjaguarpaw** [comment]
> On LTS we don't notify owners again (maybe we should?)

If I had been notified I would have been able to address this sooner. As it happened, I discovered this upper bound out of idle curiosity, whilst I was investigating LTS for unrelated reasons (adding `bluefin`). At the very least I think it would be useful to add the reason for the upper-bounding into the commit message.

**Comment by mihaimaruseac** [comment]
That makes sense. I started adding the reason in the commit message and I think other curators will too.

Meanwhile, I pushed a commit to remove the upper bound, but sadly I already did this week's LTS.

**Comment by tomjaguarpaw** [comment]
OK, thanks. That's fine, as long as everything is set up correctly to get the latest Opaleye in due course.

**Comment by juhp** [comment]
https://www.stackage.org/lts-22.42/package/opaleye-0.10.4.0
